### ISSUE TITLE
dts docs build fails on second run 

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#104]
It seems something is expected to be empty or not there but it is so you need to run `dts docs clean` to clean things first.

```
Job 'create_split_jobs-download_reveal' failed:                                                                                                                 
| OSError: [Errno 39] Directory not empty: 'duckuments-dist/AIDO/out/revealjs.tmp.3976/reveal.js-3.6.0' -> 'duckuments-dist/AIDO/out/revealjs'                  
> Traceback (most recent call last):                                                                                                                            
>   File "/usr/local/lib/python3.6/dist-packages/compmake/jobs/actions.py", line 259, in make                                                                   
>     result = job_compute(job=job, context=context)                                                                                                            
>   File "/usr/local/lib/python3.6/dist-packages/compmake/jobs/job_execution.py", line 71, in job_compute                                                       
>     user_object = command(*args, **kwargs)                                                                                                                    
>   File "/project/mcdp/src/mcdp_docs/reveal.py", line 95, in download_reveal                                                                                   
>     os.rename(actual, target)                                                                                                                                 
> OSError: [Errno 39] Directory not empty: 'duckuments-dist/AIDO/out/revealjs.tmp.3976/reveal.js-3.6.0' -> 'duckuments-dist/AIDO/out/revealjs'                  
Write "details create_split_jobs-download_reveal" to inspect the error.
```

**Comment by AndreaCensi** [comment]
ack.

**Comment by afdaniele** [comment]
still an issue
