### ISSUE TITLE
dts challenges evaluate error I don't get

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#109]
command was:

    $ dts challenges evaluate --challenge aido2-LF-sim-testing

in the tensorflow template
gave this error output:

```
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 37, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 145, in runner_local_main_
    no_cache=no_cache, no_build=no_build)
  File "/project/src/duckietown_challenges_runner/submission_build.py", line 14, in build_image
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '-t', 'dummy-org/dummy-repo', '-f', './Dockerfile', '.']' returned non-zero exit status 1.
```

**Comment by AndreaCensi** [comment]
This is a temporary docker error.
