### ISSUE TITLE
dts challenges evaluate fails at `evaluator` for ROS template

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#110]
```
evaluator$ cat combined.log 
2019-04-16T11:12:34.929315600Z INFO:aido-protocols:aido-protocols 5.0.2
2019-04-16T11:12:34.996710800Z 11:12:34|zn|__init__.py:6|<module>(): zn 2.0.2
2019-04-16T11:12:36.216528800Z 11:12:36|zj|__init__.py:5|<module>(): zj 2.0.1
2019-04-16T11:12:36.465062300Z 11:12:36|dt-world|__init__.py:12|<module>(): duckietown-world 1.0.23
2019-04-16T11:12:36.469975800Z 11:12:36|dt-world|__init__.py:20|<module>(): contracts 1.8.12 
2019-04-16T11:12:46.192110900Z 11:12:46|duckietown-challenges|__init__.py:8|<module>(): duckietown-challenges 4.0.17
2019-04-16T11:12:46.224074700Z 11:12:46|duckietown-challenges|cie_concrete.py:590|scoring_context(): Environment variables:
2019-04-16T11:12:46.224146900Z 
2019-04-16T11:12:46.224173400Z {
2019-04-16T11:12:46.224199300Z   "PATH": "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
2019-04-16T11:12:46.224223000Z   "HOSTNAME": "92f490d9cf4d",
2019-04-16T11:12:46.224258600Z   "HOME": "/fake-home/liam",
2019-04-16T11:12:46.224299600Z   "SUBMISSION_CONTAINER": "dummy-org/dummy-repo",
2019-04-16T11:12:46.224325600Z   "USER": "liam",
2019-04-16T11:12:46.224347900Z   "challenge_name": "aido2-LF-sim-testing",
2019-04-16T11:12:46.224372400Z   "challenge_step_name": "step1-simulation",
2019-04-16T11:12:46.224398700Z   "experiment_manager_parameters": "episodes_per_scenario: 1\nepisode_length_s: 15.0\nmin_episode_length_s: 0.0\nseed: 42\nphysics_dt: 0.05\nmax_failures: 2\nagent_in: /fifos/agent-in\nagent_out: /fifos/agent-out\nsim_in: /fifos/simulator-in\nsim_out: /fifos/simulator-out\nsm_in: /fifos/scenario_maker-in\nsm_out: /fifos/scenario_maker-out\n",
2019-04-16T11:12:46.224421900Z   "submission_id": "0",
2019-04-16T11:12:46.224447900Z   "uid": "501",
2019-04-16T11:12:46.224473400Z   "username": "liam",
2019-04-16T11:12:46.224499000Z   "LANG": "C.UTF-8",
2019-04-16T11:12:46.224551200Z   "GPG_KEY": "0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
2019-04-16T11:12:46.224574200Z   "PYTHON_VERSION": "3.7.3",
2019-04-16T11:12:46.224600600Z   "PYTHON_PIP_VERSION": "19.0.3",
2019-04-16T11:12:46.224652300Z   "DISABLE_CONTRACTS": "1"
2019-04-16T11:12:46.224679100Z }
2019-04-16T11:12:46.225753000Z 11:12:46|duckietown-challenges|cie_concrete.py:260|__init__(): ChallengeInterfaceEvaluatorConcrete root = /challenges
2019-04-16T11:12:46.233608100Z 11:12:46|launcher|experiment_manager.py:52|main(): parameters:
2019-04-16T11:12:46.233661200Z 
2019-04-16T11:12:46.233687100Z {'episodes_per_scenario': 1, 'episode_length_s': 15.0, 'min_episode_length_s': 0.0, 'seed': 42, 'physics_dt': 0.05, 'max_failures': 2, 'agent_in': '/fifos/agent-in', 'agent_out': '/fifos/agent-out', 'sim_in': '/fifos/simulator-in', 'sim_out': '/fifos/simulator-out', 'sm_in': '/fifos/scenario_maker-in', 'sm_out': '/fifos/scenario_maker-out'}
2019-04-16T11:12:47.701760400Z 11:12:47|znw|streams.py:13|wait_for_creation(): waiting for creation of /fifos/simulator-out
2019-04-16T11:12:49.540677700Z 11:12:49|znw|streams.py:13|wait_for_creation(): waiting for creation of /fifos/scenario_maker-out
2019-04-16T11:12:50.547493600Z 11:12:50|znw|wrapper_outside.py:62|_get_node_protocol(): My capabilities: {'z2': {'protocol-reflection': True}}
2019-04-16T11:12:50.547545300Z 11:12:50|znw|wrapper_outside.py:63|_get_node_protocol(): Found capabilities: {'z2': {}}
2019-04-16T11:12:50.547563500Z 11:12:50|znw|wrapper_outside.py:70|_get_node_protocol(): Node does not support reflection.
2019-04-16T11:12:50.548313800Z 11:12:50|znw|wrapper_outside.py:62|_get_node_protocol(): My capabilities: {'z2': {'protocol-reflection': True}}
2019-04-16T11:12:50.548361700Z 11:12:50|znw|wrapper_outside.py:63|_get_node_protocol(): Found capabilities: {'z2': {'protocol-reflection': True}}
2019-04-16T11:12:50.660673700Z 11:12:50|znw|wrapper_outside.py:62|_get_node_protocol(): My capabilities: {'z2': {'protocol-reflection': True}}
2019-04-16T11:12:50.660740300Z 11:12:50|znw|wrapper_outside.py:63|_get_node_protocol(): Found capabilities: {'z2': {'protocol-reflection': True}}
2019-04-16T11:12:50.912672900Z 11:12:50|launcher|experiment_manager.py:330|check_compatibility_between_agent_and_sim(): Simulation provides observations <class 'aido_schemas.schemas.Duckiebot1Observations'>
2019-04-16T11:12:50.912741100Z 11:12:50|launcher|experiment_manager.py:332|check_compatibility_between_agent_and_sim(): Simulation requires commands <class 'aido_schemas.schemas.Duckiebot1Commands'>
2019-04-16T11:12:50.912766600Z 11:12:50|launcher|experiment_manager.py:336|check_compatibility_between_agent_and_sim(): Cannot check compatibility of interfaces because the agent does not implement reflection.
2019-04-16T11:12:53.918268500Z 11:12:53|zj|json2cbor.py:155|wait_for_data(): I have been waiting 3.0 s. I will wait indefinitely.
2019-04-16T11:12:56.923041400Z 11:12:56|zj|json2cbor.py:155|wait_for_data(): I have been waiting 6.0 s. I will wait indefinitely.
2019-04-16T11:13:00.771260500Z 11:13:00|zj|json2cbor.py:155|wait_for_data(): I have been waiting 9.9 s. I will wait indefinitely.
2019-04-16T11:13:00.815318900Z 11:13:00|launcher|experiment_manager.py:177|main(): Anomalous error while running episodes:
2019-04-16T11:13:00.815394000Z 
2019-04-16T11:13:00.815429400Z  > Traceback (most recent call last):
2019-04-16T11:13:00.815458000Z  >   File "experiment_manager.py", line 80, in main
2019-04-16T11:13:00.815490600Z  >     sim_ci.write_topic_and_expect_zero('seed', config.seed)
2019-04-16T11:13:00.815510300Z  >   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 101, in write_topic_and_expect_zero
2019-04-16T11:13:00.815543100Z  >     nickname=self.nickname)
2019-04-16T11:13:00.815576500Z  >   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 250, in read_reply
2019-04-16T11:13:00.815603000Z  >     raise RemoteNodeAborted(msg) from None
2019-04-16T11:13:00.815630200Z  > zuper_nodes.structures.RemoteNodeAborted: Remote node closed communication (None)
2019-04-16T11:13:00.815656500Z  > 
2019-04-16T11:13:00.815685500Z 11:13:00|launcher|experiment_manager.py:183|main(): Simulation done.
2019-04-16T11:13:00.815721000Z 11:13:00|duckietown-challenges|cie_concrete.py:346|info(): evaluation: saving files
2019-04-16T11:13:00.828428600Z 11:13:00|duckietown-challenges|cie_concrete.py:599|declare(): declare error:
2019-04-16T11:13:00.828492500Z InvalidEvaluator:
2019-04-16T11:13:00.828517600Z Traceback (most recent call last):
2019-04-16T11:13:00.828545000Z   File "experiment_manager.py", line 80, in main
2019-04-16T11:13:00.828570600Z     sim_ci.write_topic_and_expect_zero('seed', config.seed)
2019-04-16T11:13:00.828597600Z   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 101, in write_topic_and_expect_zero
2019-04-16T11:13:00.828630900Z     nickname=self.nickname)
2019-04-16T11:13:00.828666400Z   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 250, in read_reply
2019-04-16T11:13:00.828693200Z     raise RemoteNodeAborted(msg) from None
2019-04-16T11:13:00.828725400Z zuper_nodes.structures.RemoteNodeAborted: Remote node closed communication (None)
2019-04-16T11:13:00.828750100Z 
2019-04-16T11:13:00.828774700Z The above exception was the direct cause of the following exception:
2019-04-16T11:13:00.828806500Z 
2019-04-16T11:13:00.828839100Z Traceback (most recent call last):
2019-04-16T11:13:00.828865500Z   File "/project/src/duckietown-challenges/src/duckietown_challenges/cie_concrete.py", line 610, in scoring_context
2019-04-16T11:13:00.828890500Z     yield cie
2019-04-16T11:13:00.828922200Z   File "experiment_manager.py", line 426, in <module>
2019-04-16T11:13:00.828954600Z     wrap(cie)
2019-04-16T11:13:00.828979100Z   File "experiment_manager.py", line 415, in wrap
2019-04-16T11:13:00.829003800Z     main(cie, logdir, attempts)
2019-04-16T11:13:00.829036000Z   File "experiment_manager.py", line 178, in main
2019-04-16T11:13:00.829061600Z     raise dc.InvalidEvaluator(msg) from e
2019-04-16T11:13:00.829086500Z duckietown_challenges.exceptions.InvalidEvaluator: Anomalous error while running episodes:
2019-04-16T11:13:00.829110900Z 
2019-04-16T11:13:00.829135400Z  > Traceback (most recent call last):
2019-04-16T11:13:00.829166800Z  >   File "experiment_manager.py", line 80, in main
2019-04-16T11:13:00.829193200Z  >     sim_ci.write_topic_and_expect_zero('seed', config.seed)
2019-04-16T11:13:00.829217900Z  >   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 101, in write_topic_and_expect_zero
2019-04-16T11:13:00.829242900Z  >     nickname=self.nickname)
2019-04-16T11:13:00.829275400Z  >   File "/project/src/zuper-nodes/src/zuper_nodes_wrapper/wrapper_outside.py", line 250, in read_reply
2019-04-16T11:13:00.829300600Z  >     raise RemoteNodeAborted(msg) from None
2019-04-16T11:13:00.829327000Z  > zuper_nodes.structures.RemoteNodeAborted: Remote node closed communication (None)
2019-04-16T11:13:00.829357800Z  > 
2019-04-16T11:13:00.829382700Z 
2019-04-16T11:13:00.846774000Z 11:13:00|duckietown-challenges|utils.py:39|write_data_to_file(): Written to: /challenges/challenge-results/challenge_results.yaml
```

**Comment by liampaull** [comment]
not enough Docker Memory - should have at least 4.5 GB
