### ISSUE TITLE
dts challenges evaluate 401 error

### ISSUE THREAD

**Issue by zvtibo** [duckietown/duckietown-shell-commands#112]
dts challenges submit works well for me.However, when I evaluate the submission locally, some error message occurs.
```
Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 37, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 143, in runner_local_main_
    cd = get_challenge_description(token, one, impersonate=parsed.impersonate)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest_methods.py", line 181, in get_challenge_description
    res = make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest.py", line 102, in make_server_request
    raise NotAuthorized(msg) from None
duckietown_challenges.rest.NotAuthorized: Not authorized to perform operation.

401 Unauthorized
```
My operating system is ubuntu 16.04.

**Comment by AndreaCensi** [comment]
which challenge?

**Comment by zvtibo** [comment]
```
You are not allowed to evaluate local the challenge "aido2-LF-real-testing".
```
```
You are not allowed to evaluate local the challenge "aido2-PRED".
```
I've tried this two, same error message.

**Comment by zvtibo** [comment]
Tried on Mac, same error, 401 Unauthorized.

**Comment by AndreaCensi** [comment]
@zvtibo can you try again with `aido2-pred` ? 
for `aido2-LF-real-testing` for now that is the expected behavior

**Comment by zvtibo** [comment]
Same error
```
DEBUG:dts:Monitoring container local-evaluator
INFO:dts:status: running
INFO:dt-challenges-runner:dt-challenges-runner 4.0.30
DEBUG:dt-challenges-runner:Default encoding utf-8
INFO:dt-challenges-runner:using: requests 2.21.0
INFO:dt-challenges-runner:using: docker-py 3.7.2
INFO:dts:duckietown-shell 4.0.21
DEBUG:dts:encoding: stdout utf8 stderr utf8 locale UTF-8.
INFO:duckietown-challenges:duckietown-challenges 4.0.19
DEBUG:runner-local:Running in directory /home/chen/duckietown/challenge-prediction/predictor_last
INFO:runner-local:I will evaluate challenge aido2-PRED


dts :  message from server: Last blog post:
    :                     : 
    :                     :   AI-DO technical updates
    :                     : https://www.duckietown.org/archives/36858
Looking for compatible and open challenges: 

  name                              protocol                          open?         title
  ----                              --------                          -----         -----
  aido2-AMOD-efficiency             aido2_amod1-v4                    open          AMOD 🤹 ‍- Efficiency 
  aido2-AMOD-fleet_size             aido2_amod1-v4                    open          AMOD 🤹 - Fleet Size
  aido2-AMOD-service_quality        aido2_amod1-v4                    open          AMOD 🤹 - Service Quality
  aido2-LF-real-testing             aido2_db18_agent-z2               open          LF 🚗 - Lane following (robotarium 🏎, testing 🥇)
  aido2-LF-real-validation          aido2_db18_agent-z2               open          LF 🚗 - Lane following (robotarium 🏎, validation 🏋)
  aido2-LF-sim-testing              aido2_db18_agent-z2               open          LF 🚗 - Lane following (simulation 👾, testing 🥇)
  aido2-LF-sim-validation           aido2_db18_agent-z2               open          LF 🚗 - Lane following  (simulation 👾, validation 🏋)
  aido2-LFV-real-testing            aido2_db18_agent-z2               open          LFV 🚗🚗 - Lane following + Vehicles (robotarium 🏎, testing 🥇)
  aido2-LFV-real-validation         aido2_db18_agent-z2               open          LFV 🚗🚗 - Lane following + Vehicles (robotarium 🏎, validation 🏋)
  aido2-LFV-sim-testing             aido2_db18_agent-z2               open          LFV 🚗🚗 - Lane following + Vehicles (simulation 👾, testing 🥇)
  aido2-LFV-sim-validation          aido2_db18_agent-z2               open          LFV 🚗🚗 - Lane following + Vehicles (simulation 👾, validation 🏋)
  aido2-LFVI-real-testing           aido2_db18_agent-z2               open          LFVI 🚗🚗🚦 - Lane following + Vehicles + Intersections (robotarium 🏎, testing 🥇)
  aido2-LFVI-real-validation        aido2_db18_agent-z2               open          LFVI 🚗🚗🚦 - Lane following + Vehicles + Intersections (robotarium 🏎, validation 🏋)
  aido2-LFVI-sim-testing            aido2_db18_agent-z2               open          LFVI 🚗🚗🚦 - Lane following + Vehicles + Intersections (simulation 👾, testing 🥇) 
  aido2-LFVI-sim-validation         aido2_db18_agent-z2               open          LFVI 🚗🚗🚦 - Lane following + Vehicles + Intersections (simulation 👾, validation 🏋) 
  aido2-PRED                        aido2_simple_predictor-z2         open          Simple prediction


Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 37, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 143, in runner_local_main_
    cd = get_challenge_description(token, one, impersonate=parsed.impersonate)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest_methods.py", line 181, in get_challenge_description
    res = make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/rest.py", line 111, in make_server_request
    raise NotAuthorized(msg) from None
duckietown_challenges.rest.NotAuthorized: Not authorized to perform operation.

401 Unauthorized




You are not allowed to evaluate local the challenge "aido2-PRED".
```

**Comment by enicky** [comment]
I have the same issue. Always getting a 401 unauthorized on the rest request when trying to get the challenge description from online ... (also ubuntu 16.04)

**Comment by liampaull** [comment]
@AndreaCensi any ideas here?

**Comment by AndreaCensi** [comment]
Solved (in Slack)

**Comment by plafer** [comment]
I got the same error again, on Ubuntu 16.04 as well (Python 3.6 and 3.7). What was the resolution?

@liampaull @AndreaCensi
