### ISSUE TITLE
keyboard_control "video system not initialized" error on exit

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#119]
When I run `dts duckiebot keyboard_control <BOTNAME>` everything works fine until I press `q` to exit, then the following error shows up:

```
Traceback (most recent call last):
  File "misc/virtualJoy/virtualJoy.py", line 194, in <module>
    loop()
  File "misc/virtualJoy/virtualJoy.py", line 108, in loop
    pygame.display.flip()
pygame.error: video system not initialized

dts :  Traceback (most recent call last):
    :    File "/home/afdaniele/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 48, in cli_main
    :      cli_main_()
    :    File "/home/afdaniele/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 126, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/afdaniele/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 410, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/afdaniele/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/afdaniele/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/afdaniele/.dt-shell/commands/duckiebot/keyboard_control/command.py", line 36, in command
    :      run_gui_controller(parsed_args.hostname, parsed_args.image)
    :    File "/home/afdaniele/.dt-shell/commands/duckiebot/keyboard_control/command.py", line 87, in run_gui_controller
    :      start_command_in_subprocess(cmd)
    :    File "/home/afdaniele/.dt-shell/commands/utils/cli_utils.py", line 30, in start_command_in_subprocess
    :      raise Exception(msg)
    :  Exception: Error occurred while running docker attach joystick_gui_pi3a, please check and retry (1).
```

I'm using:
    :  duckietown-shell-commands: 4.0.22
    :  duckietown-challenges: 4.0.30
    :  python: "3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]"
    :  duckietown-shell: 4.0.22
    :  encodings:
    :    stdout: UTF-8
    :    stderr: UTF-8
    :    locale: UTF-8

**Comment by jasonhu5** [comment]
Fixed
