### ISSUE TITLE
duckiebot demo base bug

### ISSUE THREAD

**Issue by pmirallesr** [duckietown/duckietown-shell-commands#178]
Found a bug when trying to perform wheel calibration of the duckiebot. Apparently I'm too updated for it.

```
dts duckiebot demo --demo_name base --duckiebot_name mobyduck --image duckietown/dt-core:daffy
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/pmirallesr/.dt-shell/commands-multi/daffy
INFO:duckietown-challenges:duckietown-challenges 5.1.5
INFO:zj:zuper-ipce 5.3.0
INFO:zuper-typing:zuper-typing 5.3.0
INFO:zuper-commons:zuper-commons 5.0.11
INFO:dts:duckietown-shell-commands 5.0.2
INFO:dts:Using package duckietown_demos
WARNING:dts:couldn't remove existing container: 404 Client Error: Not Found ("No such container: demo_base")
INFO:dts:Running command /bin/bash
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.37

dts :  Traceback (most recent call last):
    :    File "/home/pmirallesr/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/pmirallesr/.local/lib/python3.6/site-packages/dt_shell/main.py", line 175, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/pmirallesr/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 287, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/pmirallesr/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word], shell, " ".join(parts[1:])
    :    File "/home/pmirallesr/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 50, in do_command
    :      cls.command(shell, args)
    :    File "/home/pmirallesr/.dt-shell/commands-multi/daffy/duckiebot/demo/command.py", line 147, in command
    :      start_command_in_subprocess(attach_cmd)
    :    File "/home/pmirallesr/.dt-shell/commands-multi/daffy/utils/cli_utils.py", line 46, in start_command_in_subprocess
    :      raise Exception(msg)
    :  Exception: Error occurred while running docker -H mobyduck.local attach demo_base, please check and retry (1)

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-challenges: 5.1.5
    :  duckietown-shell-commands: 5.0.2
    :  python: "3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]"
    :  duckietown-shell: 5.1.6
    :  commands-version: daffy
    :  encodings:
    :    stdout: UTF-8
    :    stderr: UTF-8
    :    locale: UTF-8
```

**Comment by AleksandarPetrov** [comment]
@pmirallesr that indeed appears to be the case. However, I also have version 1.40 of the API and have experienced no issues. Can you share the output of `docker version` of your computer?

**Comment by pmirallesr** [comment]
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by pmirallesr** [comment]
@AleksandarPetrov Does that output tell you anything?

**Comment by pmirallesr** [comment]
I tried again after downloading dts' latest commands and it seems to work properly. Many thanks!
