### ISSUE TITLE
Failure to run dts duckiebot calibrate_intrinsics mobyduck 

### ISSUE THREAD

**Issue by pmirallesr** [duckietown/duckietown-shell-commands#183]
I encounter the following error whenever I try to launch the intrinsic calibration:
```
ERROR:dts:The demo_camera is not running on the duckiebot - please run `dts duckiebot demo --demo_name camera --package_name pi_camera --image duckietown/dt-core:daffy-arm32v7 --duckiebot_name mobyduck

```
Despite running the demo_camera with the command available at Unit C-12 and also the command mentioned in the error.
I have succesfully obtained an image from the camera via the procedure described in C-11, so the camera is operative.
I ssh'd into the robot and examined the demo_camera output. There seems to be some sort of error. The rest of the setup process did not raise any errors and essentially passed without a hitch.

```
docker logs demo_camera 
The environment variable VEHICLE_IP is set to '192.168.1.38'. Adding to /etc/hosts.
... logging to /root/.ros/log/d710a6cc-b486-11ea-bbfa-b827eb5095b4/roslaunch-mobyduck-1.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://192.168.1.38:38373/
SUMMARY
========
PARAMETERS
 * /mobyduck/decoder_node/publish_freq: 2.0
 * /mobyduck/raw_cam_info_reader_node/cali_file_name: mobyduck
 * /mobyduck/raw_cam_info_reader_node/image_type: raw
 * /mobyduck/raw_cam_info_reader_node/pub_freq: 1.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
NODES
  /mobyduck/
    decoder_node (pi_camera/decoder_node.py)
    raw_cam_info_reader_node (pi_camera/cam_info_reader_node.py)
ROS_MASTER_URI=http://192.168.1.38:11311
process[mobyduck/decoder_node-1]: started with pid [65]
process[mobyduck/raw_cam_info_reader_node-2]: started with pid [66]
Traceback (most recent call last):
  File "/code/catkin_ws/src/dt-core/packages/pi_camera/src/cam_info_reader_node.py", line 4, in <module>
    from duckietown_utils import get_duckiefleet_root
  File "/code/catkin_ws/devel/lib/python2.7/dist-packages/duckietown_utils/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/geometry/__init__.py", line 38, in <module>
    from contracts import new_contract, contract
  File "/usr/local/lib/python2.7/dist-packages/contracts/__init__.py", line 44, in <module>
    from .useful_contracts import *
  File "/usr/local/lib/python2.7/dist-packages/contracts/useful_contracts/__init__.py", line 8, in <module>
    from .numpy_specific import *    
  File "/usr/local/lib/python2.7/dist-packages/contracts/useful_contracts/numpy_specific.py", line 7, in <module>
    @new_contract
  File "/usr/local/lib/python2.7/dist-packages/contracts/__init__.py", line 28, in new_contract
    return new_contract_main(*args)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main.py", line 553, in new_contract
    new_contract_impl(identifier, function)
  File "/usr/local/lib/python2.7/dist-packages/contracts/main.py", line 563, in new_contract_impl
    from .syntax import ParseException
  File "/usr/local/lib/python2.7/dist-packages/contracts/syntax.py", line 21, in <module>
    ParserElement.enablePackrat(cache_size_limit=None)
TypeError: enablePackrat() takes no arguments (1 given)
================================================================================REQUIRED process [mobyduck/raw_cam_info_reader_node-2] has died!
process has died [pid 66, exit code 1, cmd /code/catkin_ws/src/dt-core/packages/pi_camera/src/cam_info_reader_node.py raw_cam_info_reader_node/camera_info:=camera_node/raw_camera_info raw_cam_info_reader_node/compressed_image:=camera_node/image/raw __name:=raw_cam_info_reader_node __log:=/root/.ros/log/d710a6cc-b486-11ea-bbfa-b827eb5095b4/mobyduck-raw_cam_info_reader_node-2.log].
log file: /root/.ros/log/d710a6cc-b486-11ea-bbfa-b827eb5095b4/mobyduck-raw_cam_info_reader_node-2*.log
Initiating shutdown!
================================================================================
[mobyduck/raw_cam_info_reader_node-2] killing on exit
[mobyduck/decoder_node-1] killing on exit
Traceback (most recent call last):
  File "/code/catkin_ws/src/dt-core/packages/pi_camera/src/decoder_node.py", line 3, in <module>
    from cv_bridge import CvBridge, CvBridgeError
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/__init__.py", line 6, in <module>
    from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
KeyboardInterrupt
shutting down processing monitor...
... shutting down processing monitor complete
done


```

**Comment by jasonhu5** [comment]
Not relevant now
