### ISSUE TITLE
InvalidConfiguration 

### ISSUE THREAD

**Issue by wesley34** [duckietown/duckietown-shell-commands#242]
Following this guide : https://docs.duckietown.org/daffy/AIDO/out/cm_first.html
When I run `dts challenges submit --challenge aido5-LF-sim-validation` ,
it gives me this error

15:01:31|d|duckietown_challenges_cli|cli.py:81|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 77, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 204, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_submit.py", line 132, in dt_challenges_cli_submit
    raise InvalidConfiguration(msg)
duckietown_challenges.exceptions.InvalidConfiguration: There are no compatible challenges with protocols ['aido2_db18_agent-z2'],
 or you might not have the necessary permissions.

dts :  Execution of docker image failed. Return code: 32.
    :
    :  The log is available at /tmp/duckietown/dt-shell-commands/challenges/challenges_2021_01_16_23_01_22_575641_2.txt

dts :  To report a bug, please also include the contents of /tmp/shell-debug-info.txt

**Comment by frank-qcd-qk** [comment]
Make sure you have your submission.yaml contains the protocol line like this:

```
protocol: aido2_db18_agent-z2
```
