### ISSUE TITLE
dts tok set

### ISSUE THREAD

**Issue by kvanrhein** [duckietown/duckietown-shell-commands#249]
Installing dts on Ubuntu 18.04 PC workstation and hit this response to 

dts tok set

on both PC's I tried to setup:

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

dts :  You have not specified a Duckietown version. Please use:
    :  
    :          dts --set-version <version>
    :  
    :          where <version> = daffy, master19
Traceback (most recent call last):
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    cli_main_()
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/main.py", line 179, in cli_main_
    raise UserError(msg)
dt_shell.exceptions.UserError: You have not specified a Duckietown version. Please use:

        dts --set-version <version>

        where <version> = daffy, master19
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecs/.local/bin/dts", line 33, in <module>
    sys.exit(load_entry_point('duckietown-shell==5.2.3', 'console_scripts', 'dts')())
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/main.py", line 43, in cli_main
    print_version_info()
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/main.py", line 81, in print_version_info
    from pip._internal.utils.misc import get_installed_distributions
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker

**Comment by afdaniele** [comment]
Have you specified a version using the command suggested in the error?

```
dts --set-version daffy
```

**Comment by kvanrhein** [comment]
Yes I tried that and everything else suggested in the error message on my last machine and just tried that on this machine, both with the same effect.  First of all, I didn't know if I should have version daffy or master19.  But I tried daffy just now and got an error response trying to run that command.

**Comment by kvanrhein** [comment]
Yes I tried that and everything else suggested in the error message on my
last machine and just tried that on this machine, both with the same
effect. First of all, I didn't know if I should have version daffy or
master19. But I tried daffy just now and got an error response trying to
run that command.

**Comment by kvanrhein** [comment]
Here is the full response, I was able to enter my key but still got a lot of errors:

dts --set-version daffy

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

**Comment by kvanrhein** [comment]
ecs@rm313computer8:~$ dts tok set

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/ecs/.dt-shell/commands-multi/daffy
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'exercises.init.command.DTCommand' (package='exercises.', command='init'): Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 228, in _load_commands
    klass = _load_class(spec)
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 336, in _load_class
    mod = __import__(components[0])
  File "/home/ecs/.dt-shell/commands-multi/daffy/exercises/__init__.py", line 15, in <module>
    import pip
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker


Cannot load command class 'exercises.notebooks.command.DTCommand' (package='exercises.', command='notebooks'): Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 228, in _load_commands
    klass = _load_class(spec)
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 336, in _load_class
    mod = __import__(components[0])
  File "/home/ecs/.dt-shell/commands-multi/daffy/exercises/__init__.py", line 15, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker


Cannot load command class 'exercises.build.command.DTCommand' (package='exercises.', command='build'): Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 228, in _load_commands
    klass = _load_class(spec)
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 336, in _load_class
    mod = __import__(components[0])
  File "/home/ecs/.dt-shell/commands-multi/daffy/exercises/__init__.py", line 15, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker


Cannot load command class 'exercises.test.command.DTCommand' (package='exercises.', command='test'): Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 228, in _load_commands
    klass = _load_class(spec)
  File "/home/ecs/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 336, in _load_class
    mod = __import__(components[0])
  File "/home/ecs/.dt-shell/commands-multi/daffy/exercises/__init__.py", line 15, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !

            

dts :  args: []

Please enter your Duckietown token.

It looks something like this:

    dt1-7vEuJsaxeXXXXX-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfSJnxzuJjWaANeMf4y6XSXBWTpJ7vWXXXX

To find your token, first login to duckietown.org, and open the page:

    https://www.duckietown.org/site/your-token

**Comment by kvanrhein** [comment]
Get similar errors after entering this command:

dts challenges info

**Comment by kvanrhein** [comment]
This time I edited the file config.yaml which looks like this:
docker_credentials: {}
docker_password: null
docker_username: null
duckietown_version: daffy
token_dt1: null

I am not sure why my docker stuff is empty here and don't know what to enter

then tried just dts and got error:
dts :  Problems with a command?

INFO:dts:Commands version: daffy
INFO:dts:looking at /home/ecs/.dt-shell/commands-multi/daffy
ERROR:dts:
            !   Could not load commands.
                Cannot load command class 'exercises.init.command.DTCommand' (package='exercises.', command='init'): Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'

**Comment by kvanrhein** [comment]
I get a dts prompt, and I can type in commands like
(Cmd) help

Documented commands (type help <topic>):
========================================
build_utils  data         docs       fleet         install          tok      
challenges   devel        duckiebot  hatchery      logs             uninstall
cli          diagnostics  exercises  help          stack            update   
commands     dockerhub    exit       init_sd_card  start_gui_tools  version  


(Cmd) docs
Available sub-commands are:

	clean
	build

(Cmd) version
dts version 5.2.3

But the error message is still popping up.

**Comment by Haitham-Mo** [comment]
Have you got this problem solved ???
i am still stuck with it.

**Comment by kvanrhein** [comment]
Yes, sorry I did not update.  The problem was with conflicting versions of python.  I upgraded from Ubuntu 18 to 20.4 and that fixed the Python problem, then I reloaded the commands., then I could set my version to daffy.

**Comment by Haitham-Mo** [comment]
Hello ,

Thank you for getting back to me.  I believe i got the problem solved. I kinda did the same thing you did/

Thanks again.

**Comment by liampaull** [comment]
can we close this?

**Comment by kvanrhein** [comment]
yes

**Comment by aadi-mishra** [comment]
@kvanrhein What if we don't want to upgrade from ubuntu 18 to 20.4 is there any solution?
Thanks!

**Comment by aadi-mishra** [comment]
Alright I solved my issue for Ubuntu 18.04 by using. 
`pip3 install --upgrade pip`
Then
`pip3 install paramiko`

**Comment by Haitham-Mo** [comment]
Perfect, Thank you for that.

    On Monday, March 29, 2021, 07:24:33 AM PDT, Aadi Mishra ***@***.***> wrote:  
 
 


Alright I solved my issue for Ubuntu 18.04 by using.
pip3 install --upgrade pip
