### ISSUE TITLE
DTS challenges submit throwing error

### ISSUE THREAD

**Issue by SMEAC** [duckietown/duckietown-shell-commands#256]
dts challenges info and dts tok status all work fine.  However, on the following command:
`dts challenges submit --challenge aido-hello-sim-validation`
The following error occurs:
`
~        I will submit to the challenges ['aido-hello-sim-validation']

~        

~        

22:28:20|d|duckietown_challenges_cli|cli.py:81|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 77, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 204, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_submit.py", line 160, in dt_challenges_cli_submit
    br = submission_build(
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cmd_submit_build.py", line 41, in submission_build
    raise ZException(msg, available=list(credentials))
zuper_commons.types.exceptions.ZException: Credentials for registry docker.io not available
available:
[]

dts :  Execution of docker image failed. Return code: 32.
    :  
    :  The log is available at /tmp/duckietown/dt-shell-commands/challenges/challenges_2021_03_24_23_28_13_643569_6.txt

dts :  To report a bug, please also include the contents of /tmp/shell-debug-info.txt

`

This is occuring on a fresh installation of Ubuntu 20.04 LTS, following the installation guide in edx.org Duckietown Course

**Comment by SMEAC** [comment]
As additional information, Docker is already configured.  Prior to the command above, the following had been run:
`docker login`
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 
Password: 
WARNING! Your password will be stored unencrypted in /home/xxxx/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

**Comment by SMEAC** [comment]
Fixed the problem using the info of a bug included in:
[https://stackoverflow.com/c/duckietown/questions/1312](https://stackoverflow.com/c/duckietown/questions/1312)

running 
`dts update`
followed by 
`dts challenges config --docker-username  <username> --docker-password  <password>`

Then command again and it worked.
Closing as dup and solved.
