### ISSUE TITLE
Battery Upgrade

### ISSUE THREAD

**Issue by goldbattle** [duckietown/duckietown-shell-commands#265]
I am getting an error on trying to update the battery on the `DB21M`:
```
<username>@ubuntu:~$ dts duckiebot battery upgrade duck0

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/<username>/.dt-shell/commands-multi/daffy
WARNING:dts:DO NOT unplug the battery, turn off your robot, or interrupt this command. It might cause irreversible damage to the battery.
INFO:dts:Releasing battery...
INFO:dts:Battery released!
INFO:dts:Checking battery...
==> Entrypoint
The environment variable VEHICLE_NAME is not set. Using '1fe4853079c9'.
WARNING: robot_type file does not exist. Using 'duckiebot' as default type.
WARNING: robot_configuration file does not exist.
WARNING: robot_hardware file does not exist.
<== Entrypoint
==> Launching app...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/code/dt-firmware-upgrade/packages/upgrade_helper/main.py", line 5, in <module>
    from .helper import UpgradeHelper
  File "/code/dt-firmware-upgrade/packages/upgrade_helper/helper.py", line 14, in <module>
    from battery_drivers import Battery
  File "/code/dt-device-health/packages/battery_drivers/__init__.py", line 1, in <module>
    from .battery import Battery
  File "/code/dt-device-health/packages/battery_drivers/battery.py", line 11, in <module>
    import semver
ModuleNotFoundError: No module named 'semver'
```

Is there a way for me to install this dependency myself?
I believe it is running a docker,  so I don't think I can directly edit these dependencies myself.

**Comment by jasonhu5** [comment]
It seems the dependency should have been installed since [this commit](https://github.com/duckietown/dt-device-health/commit/fbb3128908b1caced6af74e18c5e802dc6b005cd). Make sure to update the containers/images with `dts duckiebot update`. And please reopen the issue if this continues to happen.
