### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'solution/src/encoder_pose/src/odometry_activity.py'

### ISSUE THREAD

**Issue by SHIVOH** [duckietown/duckietown-shell-commands#278]
INFO:dts:Environment built!
INFO:dts:Converting the solution/04-Odometry/odometry_activity.ipynb into a Python script...
INFO:dts:Temp filtered file : /tmp/odometry_activity.ipynb

dts :  Traceback (most recent call last):
    :    File "/home/shivoh/.dt-shell/commands-multi/daffy/utils/notebook_utils.py", line 74, in convertNotebook
    :      with open(dest, "w") as fh:
    : PermissionError: [Errno 13] Permission denied: 'solution/src/encoder_pose/src/odometry_activity.py'
    :  
    :  The above exception was the direct cause of the following exception:
    :  
    :  Traceback (most recent call last):
    :    File "/home/shivoh/.local/lib/python3.8/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/shivoh/.local/lib/python3.8/site-packages/dt_shell/main.py", line 195, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/home/shivoh/anaconda3/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/shivoh/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/shivoh/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/shivoh/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 54, in do_command
    :      cls.command(shell, args)
    :    File "/home/shivoh/.dt-shell/commands-multi/daffy/exercises/build/command.py", line 152, in command
    :      convert_notebooks(config["files"])
    :    File "/home/shivoh/.dt-shell/commands-multi/daffy/utils/notebook_utils.py", line 21, in convert_notebooks
    :      convertNotebook(notebook_file, target_dir)
    :    File "/home/shivoh/.dt-shell/commands-multi/daffy/utils/notebook_utils.py", line 78, in convertNotebook
    :      raise Exception(msg) from e
    :  Exception: Cannot write to solution/src/encoder_pose/src/odometry_activity.py

dts :  To report a bug, please also include the contents of /home/shivoh/shell-debug-info.txt

Below here is the content of /home/shivoh/shell-debug-info.txt
commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.82
duckietown-shell: 5.2.8
duckietown-shell-commands: 5.3.20210414
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]"

Kindly let me know how i could resolve this issue. Sorry if this issue is too simple, i am just a beginner in the software world.

**Comment by SHIVOH** [comment]
Issue solved after deleting the whole repo and recloning. I found that the modcon was protected file initially, which denied me to write in the repository. After recloning, its back to normal and everything is working fine. I am still not sure why it was protected file in the initial cloning.
