### ISSUE TITLE
Error building the image

### ISSUE THREAD

**Issue by rayed-therap** [duckietown/duckietown-shell-commands#289]
Shell debug info:

```
commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.82
duckietown-shell: 5.2.8
duckietown-shell-commands: 5.3.20210414
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.9.5 (default, Jun  4 2021, 12:28:51) \n[GCC 7.5.0]"
```

I get this error when I run `dts challenges submit --challenge aido-hello-sim-validation`:

```
Running build... [silence is docker creating the context]
Step 1/32 : ARG AIDO_REGISTRY=docker.io
Step 2/32 : ARG ARCH=amd64
Step 3/32 : ARG MAJOR=daffy
Step 4/32 : ARG BASE_TAG=${MAJOR}-${ARCH}
Step 5/32 : FROM ${AIDO_REGISTRY}/duckietown/dt-commons:${BASE_TAG}
 ---> dca2ebb8e403
Step 6/32 : ARG PIP_INDEX_URL
 ---> Using cache
 ---> c70f1e0c682f
Step 7/32 : ENV PIP_INDEX_URL=${PIP_INDEX_URL}
 ---> Using cache
 ---> 87abd9d6797e
Step 8/32 : RUN echo PIP_INDEX_URL=${PIP_INDEX_URL}
 ---> Using cache
 ---> af26b1993c56
Step 9/32 : WORKDIR /code
 ---> Using cache
 ---> c7d46468d622
Step 10/32 : RUN pip3 install -U "pip>=20.2"
 ---> Using cache
 ---> 11696a2bf0eb
Step 11/32 : COPY requirements.* ./
 ---> Using cache
 ---> db4012d2da7d
Step 12/32 : RUN cat requirements.* > .requirements.txt
 ---> Using cache
 ---> 61ed7bb91f7b
Step 13/32 : RUN  pip3 install --use-feature=2020-resolver -r .requirements.txt
 ---> Running in 07605bb952cb
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b2df9b8e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pipdeptree/

WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b2df9ba90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pipdeptree/

WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b2df9bbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pipdeptree/

WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b2df9bd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pipdeptree/

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b2df9be80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pipdeptree/

ERROR: Could not find a version that satisfies the requirement pipdeptree==2.0.0

ERROR: No matching distribution found for pipdeptree==2.0.0

13:03:28|d|duckietown_build_utils|docker_building.py:86|_build_line():
The command '/bin/bash -c pip3 install --use-feature=2020-resolver -r .requirements.txt' returned a non-zero code: 1
13:03:28|d|duckietown_build_utils|docker_building.py:62|run_build_():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 52, in run_build_
    line = _build_line(line)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 87, in _build_line
    raise ProjectBuildError(msg)
duckietown_build_utils.docker_building.ProjectBuildError: The command '/bin/bash -c pip3 install --use-feature=2020-resolver -r .requirements.txt' returned a non-zero code: 1

13:03:28|d|duckietown_challenges_cli|cli.py:80|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 52, in run_build_
    line = _build_line(line)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 87, in _build_line
    raise ProjectBuildError(msg)
duckietown_build_utils.docker_building.ProjectBuildError: The command '/bin/bash -c pip3 install --use-feature=2020-resolver -r .requirements.txt' returned a non-zero code: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 76, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 203, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_submit.py", line 165, in dt_challenges_cli_submit
    br = submission_build(
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cmd_submit_build.py", line 67, in submission_build
    run_build(client, **args)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 33, in run_build
    run_build_(client, rm=rm, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/docker_building.py", line 70, in run_build_
    raise BuildFailed(msg, kwargs=kwargs) from e
duckietown_build_utils.docker_building.BuildFailed: An error occurred while building the project image.
kwargs:
dict[7] 
│ rm: True
│ path: /home/rayed/challenge-aido_LF-template-random
│ tag: docker.io/rayedbw/aido-submissions:2021_06_17_13_01_53
│ buildargs: {AIDO_REGISTRY: docker.io, PIP_INDEX_URL: https://pypi.org/simple}
│ labels:
│ dict[16]
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.vcs: git
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.repository: challenge-aido_LF-template-random
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.sha: 75c6f1a337936cb30d7705da7d0e76bf2eea6445-dirty
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.dirty: True
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.branch: daffy
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.url: https://github.com/duckietown/challenge-aido_LF-template-random
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.version.head: None
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.code.version.closest: None
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.build.user: rayed
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.build.host: rayed-pc
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.build.arch: x86_64
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.build.platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.env.PIP_INDEX_URL: https://pypi.org/simple
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.env.AIDO_REGISTRY: docker.io
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.template.name: template-aido
│ │ org.duckietown.label.v3.challenge-aido_LF-template-random.template.version: 0.0.0
│ nocache: False
│ pull: False


dts :  Execution of docker image failed. Return code: 32.
    :  
    :  The log is available at /tmp/rayed/duckietown/dt-shell-commands/challenges/challenges_2021_06_17_19_01_47_458677_1.txt

dts :  To report a bug, please also include the contents of /home/rayed/shell-debug-info.txt
```

**Comment by rayed-therap** [comment]
Worked after reinstalling docker and docker-compose. Thanks!
