### ISSUE TITLE
Error dts challenges evalauate give CannotGetDirInfo: Cannot get origin URL [duckietown_build_utils.commons.CannotGetDirInfo: Cannot get origin URL]

### ISSUE THREAD

**Issue by haridaspt** [duckietown/duckietown-shell-commands#296]
04:43:38|d|commons.fs|zc_fileutils.py:99|write_bytes_to_file():
already up to date requirements.resolved
04:43:38|d|duckietown_challenges_cli|cli.py:80|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/commons.py", line 61, in get_dir_info
    repo_info = get_origin_url_repo(dirname)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/commons.py", line 171, in get_origin_url_repo
    origin_url0 = _run_cmd(["git", "-C", dirname, "config", "--get", "remote.origin.url"])[0]
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/commons.py", line 177, in _run_cmd
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '-C', '/home/ubuntu/mooc-exercises/object-detection', 'config', '--get', 'remote.origin.url']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 76, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 203, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_evaluate.py", line 11, in dt_challenges_cli_evaluate
    runner_local_main_(args, token=environment.token)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner_local.py", line 206, in runner_local_main_
    solution_container = submission_build3(
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/submission_build.py", line 56, in submission_build3
    labels = get_duckietown_labels(path)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/aido_labels.py", line 24, in get_duckietown_labels
    di = get_dir_info(dirname)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_build_utils/commons.py", line 64, in get_dir_info
    raise CannotGetDirInfo(msg, **context) from e
**duckietown_build_utils.commons.CannotGetDirInfo: Cannot get origin URL**
dirname:
/home/ubuntu/mooc-exercises/object-detection

dts :  Execution of docker image failed. Return code: 32.
    :  
    :  The log is available at /tmp/ubuntu/duckietown/dt-shell-commands/challenges/challenges_2021_07_23_10_13_17_733712_5.txt

dts :  To report a bug, please also include the contents of /home/ubuntu/shell-debug-info.txt

Request any suggestions on how to proceed..

**Comment by jasonhu5** [comment]
Does the problem persist with latest dts and commands? The challenge related docker images have also been updated. If there is still problem, please reopen this
