### ISSUE TITLE
dts desktop update : Internal Server Error

### ISSUE THREAD

**Issue by Chahbaz-Aman** [duckietown/duckietown-shell-commands#297]
I keep getting this error when I try to update dts desktop. I am unable to resolve it. Please help me get around this issue so that I can complete the assignments.

INFO:dts:Pulling image `duckietown/challenge-aido_lf-template-ros:daffy-amd64`...

dts :  Traceback (most recent call last):
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    :      response.raise_for_status()
    :    File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    :      raise HTTPError(http_error_msg, response=self)
    :  requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=daffy-amd64&fromImage=duckietown%2Fchallenge-aido_lf-template-ros
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/chahbaz/.local/lib/python3.8/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/chahbaz/.local/lib/python3.8/site-packages/dt_shell/main.py", line 195, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/chahbaz/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/chahbaz/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/chahbaz/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 54, in do_command
    :      cls.command(shell, args)
    :    File "/home/chahbaz/.dt-shell/commands-multi/daffy/desktop/update/command.py", line 34, in command
    :      pull_image(image, client)
    :    File "/home/chahbaz/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 129, in pull_image
    :      for line in client.api.pull(image, stream=True, decode=True):
    :    File "/usr/lib/python3/dist-packages/docker/api/image.py", line 415, in pull
    :      self._raise_for_status(response)
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    :      raise create_api_error_from_http_exception(e)
    :    File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    :      raise cls(e, response=response, explanation=explanation)
    :  docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution")

shell-debug-info:
commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.82
duckietown-shell: 5.2.8
duckietown-shell-commands: 5.3.20210414
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.8.10 (default, Jun  2 2021, 10:49:15) \n[GCC 9.4.0]"

**Comment by Chahbaz-Aman** [comment]
It is a simple internet access issue. Ensuring that the downloads do not stop or pause at any point due to the OS locking the PC or any other reason solved the problem.
