### ISSUE TITLE
dts launch fails - Error:dts:   Could not load commands.   ...

### ISSUE THREAD

**Issue by pgaston1** [duckietown/duckietown-shell-commands#300]
dts launches, throws lots of errors in red - then continues working...     Any idea on how I configured incorrectly?
(I thought I followed instructions...  though, btw there is no folder ~/.dt-shell/commands - the only folder is 'commands-multi')
Ubuntu 18.    Already have NVidia TLT working (e.g., NVidia docker installed, working.)
```

$ dts

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/pg/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/pg/.local/lib/python3.6/site-packages
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'exercises.build.command.DTCommand' (package='exercises.', command='build'): Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (websocket-client 1.1.0 (/home/pg/.local/lib/python3.6/site-packages), Requirement.parse('websocket-client<1,>=0.32.0'), {'docker-compose'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pg/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 228, in _load_commands
    klass = _load_class(spec)

```
**etc. etc.**   
```

            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !


```            
**then...works fine (?)**
```
?
Welcome to the Duckietown Shell (5.2.8).

Type "help" or "?" to list commands.


(Cmd) ?

Documented commands (type help <topic>):
========================================
build_utils  desktop      duckiebot  help          social           update 
challenges   devel        exercises  init_sd_card  stack            version
cli          diagnostics  exit       install       start_gui_tools
commands     dockerhub    fleet      logs          tok            
data         docs         hatchery   map           uninstall      


(Cmd) 
```

**Comment by s-zaman-eng** [comment]
try 
`sudo -H pip3 install --upgrade pip`
and/or
`pip3 install --upgrade setuptools pip`

worked for me.
