### ISSUE TITLE
dts: not working (already tried uninstalling)

### ISSUE THREAD

**Issue by vsancnaj** [duckietown/duckietown-shell-commands#319]
`xxxxxx:~$ dts
Traceback (most recent call last):
  File "/home/vsanchez/.local/bin/dts", line 5, in <module>
    from dt_shell import cli_main
  File "/home/vsanchez/.local/lib/python3.8/site-packages/dt_shell/__init__.py", line 33, in <module>
    from .cli import DTShell
  File "/home/vsanchez/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 13, in <module>
    from .commands_ import (
  File "/home/vsanchez/.local/lib/python3.8/site-packages/dt_shell/commands_.py", line 9, in <module>
    from .config import remoteurl_from_RepoInfo, RepoInfo
  File "/home/vsanchez/.local/lib/python3.8/site-packages/dt_shell/config.py", line 8, in <module>
    from .constants import DTShellConstants
  File "/home/vsanchez/.local/lib/python3.8/site-packages/dt_shell/constants.py", line 33, in <module>
    Duckietown=termcolor.colored(DNAME, "yellow", attrs=["bold"]), version=__version__
AttributeError: module 'termcolor' has no attribute 'colored'
`

**Comment by liampaull** [comment]
can you please provide instructions to reproduce?

**Comment by jasonhu5** [comment]
If this is still an issue with latest `dts` and commands, please feel free to reopen the issue
