### ISSUE TITLE
dts challenges evaluate  --challenge aido-LF-sim-validation gives errors: Could not read submission info.

### ISSUE THREAD

**Issue by bberrevoets** [duckietown/duckietown-shell-commands#346]
When i run the command as described in [The Docs](https://docs.duckietown.org/daffy/AIDO/out/cm_first.html), the command gives the following error.

```
dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/bert/.dt-shell/commands-multi/daffy

dts :  An updated version of the commands is available.
    :  
    :  Attempting auto-update.

dts :  Updating commands...

dts :  OK
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /home/bert/.local/lib/python3.10/site-packages
DEBUG:duckietown_docker_utils:repo_root='/home/bert/challenge-aido_LF-template-random' pwd='/home/bert/challenge-aido_LF-template-random' pwd1='/home/bert/challenge-aido_LF-template-random'
DEBUG:duckietown_docker_utils:/home/bert/.gitconfig -> /tmp/tmpdeuyrjc2/fake-home/.gitconfig
DEBUG:duckietown_docker_utils:/home/bert/.dt-shell -> /tmp/tmpdeuyrjc2/fake-home/.dt-shell
DEBUG:commons:version: 6.2.4 *
DEBUG:typing:version: 6.2.3
DEBUG:duckietown_challenges_cli:duckietown_challenges_cli version 6.0.119 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges:duckietown_challenges version 6.5.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_build_utils:duckietown_build_utils version 6.2.78 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /usr/local/lib/python3.8/dist-packages
DEBUG:ipce:version 6.1.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges_runner:duckietown_challenges_runner version 6.2.40 path /usr/local/lib/python3.8/dist-packages
10:06:08|d|duckietown_challenges_cli|cli.py:178|dt_challenges_cli_main_():
Using CREDENTIALS environment variable
10:06:08|d|duckietown_challenges_cli|cli.py:213|dt_challenges_cli_main_():
 credentials_available: [docker.io]
10:06:08|d|duckietown_challenges_cli|cli.py:79|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges/submission_read.py", line 32, in read_submission_info
    data = read_yaml_file(fn)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges/yaml_utils.py", line 22, in read_yaml_file
    with open(fn) as f:
IsADirectoryError: [Errno 21] Is a directory: '.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 75, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 229, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_evaluate.py", line 11, in dt_challenges_cli_evaluate
    runner_local_main_(args, token=environment.token)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner_local.py", line 138, in runner_local_main_
    sub_info = read_submission_info(path)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges/submission_read.py", line 35, in read_submission_info
    raise CouldNotReadSubInfo(msg) from e
duckietown_challenges.submission_read.CouldNotReadSubInfo: Could not read submission info.


dts :  Execution of docker image failed. Return code: 32.
    :  
    :  The log is available at /tmp/bert/duckietown/dt-shell-commands/challenges/challenges_2022_12_09_11_06_07_341856_9.txt

dts :  To report a bug, please also include the contents of /home/bert/shell-debug-info.txt
```
And here is the contents of the shell-debug-info.txt

```
commands-version: daffy
dt-authentication-daffy: 0.1.16
dt-data-api-daffy: 1.1.3
duckietown-docker-utils-daffy: 6.1.1
duckietown-shell: 5.4.3
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

**Comment by liampaull** [comment]
can you tell me which command you ran to get this? was it `dts devel run`?

**Comment by liampaull** [comment]
I can't reproduce this - are you sure that you entered the folder that you cloned? It seems like maybe there is no submission.yaml file from wherever you are running.

**Comment by bberrevoets** [comment]
I have executed the command `dts challenges submit --challenge aido-hello-sim-validation` in the directory `challenge-aido_LF-template-random`, i followed the following. [instructions](https://docs.duckietown.org/daffy/AIDO/out/cm_first.html)

**Comment by liampaull** [comment]
do you mean `evaluate`?

**Comment by bberrevoets** [comment]
Yes, i'am sorry.  The command is:
`dts challenges evaluate  --challenge aido-LF-sim-validation`

**Comment by bberrevoets** [comment]
I have now a new computer, so i had to install everything again, and the problem is not showing anymore, so i do not know what the problem was.
