### ISSUE TITLE
dts challenges evlauator results in FileNotFoundError

### ISSUE THREAD

**Issue by gabenaghi** [duckietown/duckietown-shell-commands#349]
Was able to submit challenge without an issue. Tried evaluating also (just for good measure), but results in FileNotFoundError. This is after successfully running 'pip3 install -U duckietown-challenges-runner-daffy'

[shell-debug-info.txt](https://github.com/duckietown/duckietown-shell-commands/files/10254537/shell-debug-info.txt)

```
gabe@gabe-MacBookAir:~/duckietown/challenge-aido_LF-template-random$ dts challenges evaluator --submission 19306

 dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/gabe/.dt-shell/commands-multi/daffy
None
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.97 path /home/gabe/.local/lib/python3.8/site-packages
DEBUG:duckietown_docker_utils:repo_root='/home/gabe/duckietown/challenge-aido_LF-template-random' pwd='/home/gabe/duckietown/challenge-aido_LF-template-random' pwd1='/home/gabe/duckietown/challenge-aido_LF-template-random'
DEBUG:duckietown_docker_utils:/home/gabe/.dt-shell -> /tmp/tmpgxylt53h/fake-home/.dt-shell
DEBUG:duckietown_docker_utils:Need to pull docker.io/duckietown/duckietown-challenges-cli:daffy because passed 1639 > 600 seconds.
INFO:duckietown_docker_utils:'docker.io/duckietown/duckietown-challenges-cli:daffy'
name 'docker.io/duckietown/duckietown-challenges-cli'
tag 'daffy'
sha None
pull duckietown-challenges-cli:daffy   0% |                    | ETA:  --:--:--DEBUG:commons:version: 6.2.4 *
DEBUG:typing:version: 6.2.3
DEBUG:duckietown_challenges_cli:duckietown_challenges_cli version 6.0.119 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges:duckietown_challenges version 6.5.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_build_utils:duckietown_build_utils version 6.2.78 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /usr/local/lib/python3.8/dist-packages
DEBUG:ipce:version 6.1.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges_runner:duckietown_challenges_runner version 6.3.0 path /usr/local/lib/python3.8/dist-packages
19:56:21|d|duckietown_challenges_cli|cli.py:178|dt_challenges_cli_main_():
Using CREDENTIALS environment variable
19:56:21|d|duckietown_challenges_cli|cli.py:213|dt_challenges_cli_main_():
 credentials_available: [docker.io]
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_CONTINUOUS - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_PULL - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_UPLOAD - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_DELETE - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_CACHE - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_MACHINE_ID, using default v='machine-id' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_NAME, using default v='name' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_IMPERSONATE, using default v='impersonate' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_QUOTA_CPU, using default v='quota-cpu' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_TMPDIR, using default v='tmpdir' = '/tmp/gabe/duckietown-challenges-runner'
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_CREDENTIALS, using default v='credentials' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_FEATURES, using default v='features' = '{}'
19:56:21|d|duckietown_challenges_runner|runner.py:264|dt_challenges_evaluator_():
copy_to_machine_cache = True
19:56:22|d|duckietown_challenges_cli|cli.py:79|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 75, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 229, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_evaluator.py", line 11, in dt_challenges_cli_evaluator
    dt_challenges_evaluator_(args, token=environment.token)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 397, in dt_challenges_evaluator_
    go_(
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 624, in go_
    features = get_features(more_features, tmpdir=tmpdir, use_ipfs=use_ipfs)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 469, in get_features
    disk = psutil.disk_usage(tmpdir)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2083, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 131, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gabe/duckietown-challenges-runner'

DEBUG:commons:version: 6.2.4 *
DEBUG:typing:version: 6.2.3
DEBUG:duckietown_challenges_cli:duckietown_challenges_cli version 6.0.119 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges:duckietown_challenges version 6.5.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_build_utils:duckietown_build_utils version 6.2.78 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /usr/local/lib/python3.8/dist-packages
DEBUG:ipce:version 6.1.2 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges_runner:duckietown_challenges_runner version 6.3.0 path /usr/local/lib/python3.8/dist-packages
19:56:21|d|duckietown_challenges_cli|cli.py:178|dt_challenges_cli_main_():
Using CREDENTIALS environment variable
19:56:21|d|duckietown_challenges_cli|cli.py:213|dt_challenges_cli_main_():
 credentials_available: [docker.io]
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_CONTINUOUS - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_PULL - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_UPLOAD - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_DELETE - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:123|get_truthy_value_or_default():
not found DT_RUNNER_NO_CACHE - default = False
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_MACHINE_ID, using default v='machine-id' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_NAME, using default v='name' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_IMPERSONATE, using default v='impersonate' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_QUOTA_CPU, using default v='quota-cpu' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_TMPDIR, using default v='tmpdir' = '/tmp/gabe/duckietown-challenges-runner'
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_CREDENTIALS, using default v='credentials' = None
19:56:21|d|duckietown_challenges_runner|runner.py:144|get_env_value_or_none():
not found DT_RUNNER_FEATURES, using default v='features' = '{}'
19:56:21|d|duckietown_challenges_runner|runner.py:264|dt_challenges_evaluator_():
copy_to_machine_cache = True
19:56:22|d|duckietown_challenges_cli|cli.py:79|dt_challenges_cli_main():
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 75, in dt_challenges_cli_main
    dt_challenges_cli_main_(args=args, sections=sections, main_cmd="challenges")
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli.py", line 229, in dt_challenges_cli_main_
    f(rest, environment)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_cli/cli_evaluator.py", line 11, in dt_challenges_cli_evaluator
    dt_challenges_evaluator_(args, token=environment.token)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 397, in dt_challenges_evaluator_
    go_(
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 624, in go_
    features = get_features(more_features, tmpdir=tmpdir, use_ipfs=use_ipfs)
  File "/usr/local/lib/python3.8/dist-packages/duckietown_challenges_runner/runner.py", line 469, in get_features
    disk = psutil.disk_usage(tmpdir)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2083, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 131, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gabe/duckietown-challenges-runner'


dts :  Execution of docker image failed. Return code: 32.
    :  
    :  The log is available at /tmp/gabe/duckietown/dt-shell-commands/challenges/challenges_2022_12_18_11_56_18_648534_3.txt

dts :  To report a bug, please also include the contents of /home/gabe/shell-debug-info.txt

```

**Comment by AndreaCensi** [comment]
Hi, could you try creating the folder `/tmp/gabe/duckietown-challenges-runner` and try again?

Also, question: you said you run `pip3 install -U duckietown-challenges-runner-daffy` but you didn't find this in the instructions, right? You are not supposed to; the code is inside a container.

**Comment by AndreaCensi** [comment]
by the way, a more consistent fix will be available in ~1 hour

**Comment by jasonhu5** [comment]
Hi @gabenaghi , have you tried to reproduce this after the above info/fixes? Is there anything remaining on this issue?

**Comment by gabenaghi** [comment]
@jasonhu5 @AndreaCensi thank you! this resolved the issue.
