### ISSUE TITLE
dts matrix install returns *** Unknown syntax: matrix install

### ISSUE THREAD

**Issue by roger-creus** [duckietown/duckietown-shell-commands#441]

**Comment by ozgurovic** [comment]
!   Could not load commands.

                Cannot load command class 'disk_image.create.command.DTCommand' (package='disk_image.', command='create'): Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 375, in _load_class
    mod = getattr(mod, comp)
AttributeError: module 'disk_image' has no attribute 'create'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 238, in _load_commands
    klass = _load_class(spec)
  File "/home/USER/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 380, in _load_class
    raise AttributeError(msg)
AttributeError: Could not get field 'create' of module 'disk_image': module 'disk_image' has no attribute 'create'	
 - Module file /home/USER/dt-shell/commands-multi/ente/disk_image/__init__.py;
 - Module content ['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__'];


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands-multi
            !
            !

**Comment by ozgurovic** [comment]
after some play around and find out, this is the branch that works with virtual duckietown ente version: 
duckietown-shell-commands-ente-fixing-duckiebot-virtual-attach-DTSW-3493
