### ISSUE TITLE
Problem in Viewing an Image Stream on Your Laptop

### ISSUE THREAD

**Issue by hanxuel** [duckietown/duckietown-shell-commands#47]
I update the dts command, when I'm trying to view the image stream, I launch 
$ docker -H hostname.local run -it --name ros-picam --network=host  --device /dev/vchiq -v /data:/data  duckietown/rpi-duckiebot-ros-picam:master18
and it works, but then in the new terminal, when I launch dts start_gui_tools hostname,it has the followin problem:

INFO:dts:duckietown-shell 3.0.19

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
Duckietown Shell commands version 1.0.4
access control disabled, clients can connect from any host
Traceback (most recent call last):
  File "/home/haliang/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 72, in cli_main
    shell.onecmd(cmdline)
  File "/home/haliang/anaconda2/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/haliang/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 405, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/haliang/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    cls.command(shell, args)
  File "/home/haliang/.dt-shell/commands/start_gui_tools/command.py", line 36, in command
    start_gui_tools(parsed_args.hostname)
  File "/home/haliang/.dt-shell/commands/start_gui_tools/command.py", line 62, in start_gui_tools
    env_vars=env_vars)
  File "/home/haliang/.local/lib/python2.7/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/haliang/.local/lib/python2.7/site-packages/docker/models/containers.py", line 823, in create
    create_kwargs = _create_container_args(kwargs)
  File "/home/haliang/.local/lib/python2.7/site-packages/docker/models/containers.py", line 1036, in _create_container_args
    raise create_unexpected_kwargs_error('run', kwargs)
TypeError: run() got an unexpected keyword argument 'env_vars'

Anybody has the idea of how to fix it? Thank you

**Comment by BensonKuan** [comment]
Faced the same issue
Tried to change 'env_vars' to 'environment' 
Error messages disappeared however the code exits without doing anything 
Therefore problem is still unsolved

**Comment by AleksandarPetrov** [comment]
@AndreaCensi The change @BensonKuan mentions was in `start_gui_tools/command.py`. It seems that it was a typo looking at [this](https://docker-py.readthedocs.io/en/stable/containers.html). I haven't changed it though as it doesn't solve the problem.

**Comment by AndreaCensi** [comment]
definitely change it. (wonder how it worked before...)
