### ISSUE TITLE
Can not initialize SD card

### ISSUE THREAD

**Issue by Petrolkopf** [duckietown/duckietown-shell-commands#50]
Traceback (most recent call last):
  File "/home/dieselkopf/.local/lib/python3.7/site-packages/dt_shell/__init__.py", line 72, in cli_main
    shell.onecmd(cmdline)
  File "/home/dieselkopf/anaconda3/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/dieselkopf/.local/lib/python3.7/site-packages/dt_shell/cli.py", line 405, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/dieselkopf/.local/lib/python3.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    cls.command(shell, args)
  File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 170, in command
    check_docker_environment()
  File "/home/dieselkopf/.local/lib/python3.7/site-packages/dt_shell/env_checks.py", line 20, in check_docker_environment
    check_user_in_group('docker')
  File "/home/dieselkopf/.local/lib/python3.7/site-packages/dt_shell/env_checks.py", line 67, in check_user_in_group
    msg += '\n\nIt belongs to groups: %s.' % ", ".join(sorted(active_groups))
TypeError: sequence item 0: expected str instance, bytes found

**Comment by gibernas** [comment]
It seems like you are using Python 3, you should use Python 2.7 instead.

**Comment by AndreaCensi** [comment]
We are trying to support Python 3.
You found a bug that will be fixed in the next release.

**Comment by AndreaCensi** [comment]
The immediate problem is that you are not in the group "docker".
