### ISSUE TITLE
Error:dts could not load commands

### ISSUE THREAD

**Issue by AmaurX** [duckietown/duckietown-shell-commands#58]
After updating the DTS to version 1.0.14, I get the following error for any command:

```
Duckietown Shell commands version 1.0.14
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'challenges.reset.command.DTCommand' (package='challenges.', command='reset'): Traceback (most recent call last):
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 388, in _load_commands
    klass = self._load_class(spec)
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 370, in _load_class
    mod = __import__(components[0])
  File "/home/amaury/.dt-shell/commands/challenges/__init__.py", line 6, in <module>
    from .submit import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/__init__.py", line 1, in <module>
    from .command import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/command.py", line 12, in <module>
    from dt_shell.utils import format_exception
ImportError: cannot import name format_exception


Cannot load command class 'challenges.info.command.DTCommand' (package='challenges.', command='info'): Traceback (most recent call last):
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 388, in _load_commands
    klass = self._load_class(spec)
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 370, in _load_class
    mod = __import__(components[0])
  File "/home/amaury/.dt-shell/commands/challenges/__init__.py", line 6, in <module>
    from .submit import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/__init__.py", line 1, in <module>
    from .command import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/command.py", line 12, in <module>
    from dt_shell.utils import format_exception
ImportError: cannot import name format_exception


Cannot load command class 'challenges.evaluate.command.DTCommand' (package='challenges.', command='evaluate'): Traceback (most recent call last):
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 388, in _load_commands
    klass = self._load_class(spec)
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 370, in _load_class
    mod = __import__(components[0])
  File "/home/amaury/.dt-shell/commands/challenges/__init__.py", line 6, in <module>
    from .submit import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/__init__.py", line 1, in <module>
    from .command import *
  File "/home/amaury/.dt-shell/commands/challenges/submit/command.py", line 12, in <module>
    from dt_shell.utils import format_exception
ImportError: cannot import name format_exception

....

Cannot load command class 'init_sd_card.command.DTCommand' (package='', command='init_sd_card'): Traceback (most recent call last):
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 388, in _load_commands
    klass = self._load_class(spec)
  File "/home/amaury/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 370, in _load_class
    mod = __import__(components[0])
  File "/home/amaury/.dt-shell/commands/init_sd_card/__init__.py", line 1, in <module>
    from .command import *
  File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 56, in <module>
    from future import builtins
ImportError: No module named future


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !    

            
*** Unknown syntax: update
```

So I tried tro delete the ~/dt-shell/commands but it still give the same errors after updating.

What is weird is also that some command give these errors and then still work (keyboard control for instance)

**Comment by AleksandarPetrov** [comment]
@AndreaCensi, shouldn't it be 
`import builtins`
Or
`from __future__ import builtins`
?

**Comment by AndreaCensi** [comment]
@AleksandarPetrov that is also valid

@AmaurX I suspect you didn't updated the shell itself. Can you update the package duckietown-shell?

**Comment by AmaurX** [comment]
@AndreaCensi That was it. In the past, the shell commands would warn me of a newer version of the shell, but not this time. Maybe something to look at in term of retro-compatibility?
