### ISSUE TITLE
Error `dts challenges follow`

### ISSUE THREAD

**Issue by takeitallsource** [duckietown/duckietown-shell-commands#59]
When I try to follow my submission status I get the following error:

```
dts :  Traceback (most recent call last):
    :    File "/home/linuxpotter/research/ai-do/dt-env-developer/.aido-env/local/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/linuxpotter/research/ai-do/dt-env-developer/.aido-env/local/lib/python2.7/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/linuxpotter/research/ai-do/dt-env-developer/.aido-env/local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/linuxpotter/research/ai-do/dt-env-developer/.aido-env/local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/linuxpotter/research/ai-do/dt-env-developer/.aido-env/local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    :      cls.command(shell, args)
    :    File "/home/linuxpotter/.dt-shell/commands/challenges/follow/command.py", line 36, in command
    :      follow_submission(token, submission_id)
    :    File "/home/linuxpotter/.dt-shell/commands/challenges/follow/command.py", line 53, in follow_submission
    :      complete = status_details['complete']
    :  KeyError: 'complete'

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.29
    :  duckietown-shell-commands: 1.0.14
    :  python: "2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]"

```

**Comment by AndreaCensi** [comment]
thanks for reporting

should be fixed in 4 minutes
