### ISSUE TITLE
`dts challenges submit` works but `dts challenges evaluate` does not

### ISSUE THREAD

**Issue by jonPlante** [duckietown/duckietown-shell-commands#62]
```
 dts challenges evaluate
INFO:dts:duckietown-shell 3.0.30

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
Duckietown Shell commands version 1.0.15
/home/jon/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEBUG:dts:Checking docker environment for user jon
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /home/jon/challenge-aido1_LF1-template-random_JP_2/output
  b2: /home/jon
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /home/jon/challenge-aido1_LF1-template-random_JP_2/output
  b2: /home/jon/challenge-aido1_LF1-template-random_JP_2
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /home/jon/.dt-shell
  b2: /home/jon
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /home/jon/challenge-aido1_LF1-template-random_JP_2
  b2: /home/jon
DEBUG:dts:Volumes:

/etc/group:
  bind: /etc/group
  mode: ro
/home/jon/.dt-shell:
  bind: /home/jon/.dt-shell
  mode: ro
/home/jon/challenge-aido1_LF1-template-random_JP_2:
  bind: /home/jon/challenge-aido1_LF1-template-random_JP_2
  mode: ro
/home/jon/challenge-aido1_LF1-template-random_JP_2/output:
  bind: /home/jon/challenge-aido1_LF1-template-random_JP_2/output
  mode: rw
/tmp:
  bind: /tmp
  mode: rw
/tmp/fake-jon-home:
  bind: /home/jon
  mode: rw
/var/run/docker.sock:
  bind: /var/run/docker.sock
  mode: rw

DEBUG:dts:Environment:

HOME: /home/jon
USER: jon
uid: 1000
username: jon

INFO:dts:The server URL is: https://challenges.duckietown.org/v3
INFO:dts:Updating container duckietown/dt-challenges-evaluator:v3
INFO:dts:This might take some time.
INFO:dts:Starting container local-evaluator with duckietown/dt-challenges-evaluator:v3
INFO:dts:Container command: dt-challenges-evaluate-local --output output
INFO:dts:Parameters:
{
    "network_mode": "host", 
    "tty": false, 
    "name": "local-evaluator", 
    "remove": true, 
    "environment": {
        "username": "jon", 
        "uid": 1000, 
        "token_dt1": "dt1-daZUHiuSz7CWgJAWfxtuk8jgJxjVqeYuoT21XsjNSTZHW-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfWGNQ5Gzc2DkxymnUdPXqXtqS5szKMtqey", 
        "DTSERVER": "https://challenges.duckietown.org/v3", 
        "USER": "jon", 
        "HOME": "/home/jon"
    }, 
    "working_dir": "/home/jon/challenge-aido1_LF1-template-random_JP_2", 
    "command": [
        "dt-challenges-evaluate-local", 
        "--output", 
        "output"
    ], 
    "user": 1000, 
    "volumes": {
        "/etc/group": {
            "bind": "/etc/group", 
            "mode": "ro"
        }, 
        "/tmp": {
            "bind": "/tmp", 
            "mode": "rw"
        }, 
        "/tmp/fake-jon-home": {
            "bind": "/home/jon", 
            "mode": "rw"
        }, 
        "/home/jon/challenge-aido1_LF1-template-random_JP_2/output": {
            "bind": "/home/jon/challenge-aido1_LF1-template-random_JP_2/output", 
            "mode": "rw"
        }, 
        "/var/run/docker.sock": {
            "bind": "/var/run/docker.sock", 
            "mode": "rw"
        }, 
        "/home/jon/.dt-shell": {
            "bind": "/home/jon/.dt-shell", 
            "mode": "ro"
        }, 
        "/home/jon/challenge-aido1_LF1-template-random_JP_2": {
            "bind": "/home/jon/challenge-aido1_LF1-template-random_JP_2", 
            "mode": "ro"
        }
    }, 
    "detach": true, 
    "group_add": [
        4, 
        24, 
        27, 
        30, 
        46, 
        113, 
        128, 
        999
    ]
}
DEBUG:dts:Monitoring container local-evaluator
INFO:dts:status: running
INFO:dt-challenges-runner:dt-challenges-runner 3.1.52
INFO:dts:duckietown-shell 3.0.30
INFO:duckietown-challenges:duckietown-challenges 3.2.12
DEBUG:runner-local:Running in directory /home/jon/challenge-aido1_LF1-template-random_JP_2
DEBUG:dts:Checking docker environment for user jon
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 93, in runner_local_main_
    result = get_challenge_description(token, subinfo.challenge_name)
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 189, in get_challenge_description
    return make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-shell/lib/dt_shell/remote.py", line 80, in make_server_request
    res = urllib.request.urlopen(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

```

docker container : https://hub.docker.com/r/jonplante/aido1_lf1_r3-v3-submission/

**Comment by AndreaCensi** [comment]
This might have been due to temporary capacity problems.
Does it still happen?

**Comment by jonPlante** [comment]
it works now

**Comment by breandan** [comment]
Great. In the long run, it would be nice to run `dts evaluate` without needing an internet connection.
