### ISSUE TITLE
SSL Error in `init_sd_card`

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#64]
I see the following error while trying to flash an SD card:

```
['docker', 'tag', 'sha256:95133c4014bf150beddbdd31ad56d12f58d1957f8a326113eb0ad844a65a7ada', 'duckietown/rpi-duckiebot-joystick-demo:master18']

dts :  Traceback (most recent call last):
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 108, in cli_main_
    :      shell.cmdloop()
    :    File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    :      stop = self.onecmd(line)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 52, in do_command
    :      cls.command(shell, args)
    :    File "/home/duckietown/.dt-shell/commands/init_sd_card/command.py", line 190, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/duckietown/.dt-shell/commands/init_sd_card/command.py", line 476, in step_setup
    :      validate_user_data(user_data_yaml)
    :    File "/home/duckietown/.dt-shell/commands/init_sd_card/command.py", line 967, in validate_user_data
    :      r = requests.put(url, data=user_data_yaml)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/requests/api.py", line 131, in put
    :      return request('put', url, data=data, **kwargs)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    :      return session.request(method=method, url=url, **kwargs)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    :      resp = self.send(prep, **send_kwargs)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    :      r = adapter.send(request, **kwargs)
    :    File "/home/duckietown/.local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    :      raise SSLError(e, request=request)
    :  SSLError: HTTPSConnectionPool(host='validate.core-os.net', port=443): Max retries exceeded with url: /validate (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
```

I'm using:
```
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.0.15
    :  python: "2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]"
```

**Comment by afdaniele** [comment]
It looks like `validate.core-os.net` is down.

**Comment by afdaniele** [comment]
@breandan can we do the validation locally?

**Comment by breandan** [comment]
Fixed. It it possible to validate locally if [`docker-compose`](https://docs.docker.com/compose/install/) is available, which is the solution we are currently using.
