### ISSUE TITLE
error challenge evaluate

### ISSUE THREAD

**Issue by placaille** [duckietown/duckietown-shell-commands#69]
I'm getting the following error when using `dts challenges evaluate`. Important to point out that `dts challenges submit` works with the same submission.

```
dts challenges evaluate
INFO:dts:duckietown-shell 3.0.30

dts :  Problems with a command?
    :
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :
    :  Troubleshooting:
    :
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :
    :    (Note: you will have to re-configure.)
Duckietown Shell commands version 1.1.1
DEBUG:dts:Checking docker environment for user phil
WARNING:dts:No group docker defined.
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output
  b2: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output
  b2: /Users/phil
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown
  b2: /Users/phil
WARNING:dts:Warning, it might be a problem to have binds with overlap
  b1: /Users/phil/.dt-shell
  b2: /Users/phil
DEBUG:dts:Volumes:

/Users/phil/.dt-shell:
  bind: /Users/phil/.dt-shell
  mode: ro
/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown:
  bind: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown
  mode: ro
/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output:
  bind: /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output
  mode: rw
/etc/group:
  bind: /etc/group
  mode: ro
/tmp:
  bind: /tmp
  mode: rw
/tmp/fake-phil-home:
  bind: /Users/phil
  mode: rw
/var/run/docker.sock:
  bind: /var/run/docker.sock
  mode: rw

DEBUG:dts:Environment:

HOME: /Users/phil
USER: phil
uid: 501
username: phil

INFO:dts:The server URL is: https://challenges.duckietown.org/v3
INFO:dts:Updating container duckietown/dt-challenges-evaluator:v3
INFO:dts:This might take some time.
INFO:dts:Starting container local-evaluator with duckietown/dt-challenges-evaluator:v3
INFO:dts:Container command: dt-challenges-evaluate-local --output output
INFO:dts:Parameters:
{
    "working_dir": "/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown",
    "user": 501,
    "group_add": [],
    "command": [
        "dt-challenges-evaluate-local",
        "--output",
        "output"
    ],
    "tty": false,
    "volumes": {
        "/var/run/docker.sock": {
            "bind": "/var/run/docker.sock",
            "mode": "rw"
        },
        "/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output": {
            "bind": "/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown/output",
            "mode": "rw"
        },
        "/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown": {
            "bind": "/Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown",
            "mode": "ro"
        },
        "/tmp": {
            "bind": "/tmp",
            "mode": "rw"
        },
        "/Users/phil/.dt-shell": {
            "bind": "/Users/phil/.dt-shell",
            "mode": "ro"
        },
        "/tmp/fake-phil-home": {
            "bind": "/Users/phil",
            "mode": "rw"
        },
        "/etc/group": {
            "bind": "/etc/group",
            "mode": "ro"
        }
    },
    "environment": {
        "username": "phil",
        "uid": 501,
        "USER": "phil",
        "HOME": "/Users/phil",
        "DTSERVER": "https://challenges.duckietown.org/v3",
        "token_dt1": "dt1-daZUHiuSz7CWgJ4XGQonvotdSxHr9wBweW8t1sgiikc52-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfWaTydwcE4X5rRz2G4jzdXiM36ehBtg8iv"
    },
    "remove": true,
    "network_mode": "host",
    "detach": true,
    "name": "local-evaluator"
}
DEBUG:dts:Monitoring container local-evaluator
INFO:dts:status: running
INFO:dt-challenges-runner:dt-challenges-runner 3.1.55
INFO:dts:duckietown-shell 3.0.30
INFO:duckietown-challenges:duckietown-challenges 3.2.14
DEBUG:runner-local:Running in directory /Users/phil/Repos/duckietown/private-challenge-aido1_LF1-baseline-duckietown
DEBUG:dts:Checking docker environment for user phil
WARNING:dts:No group docker defined.
Sending build context to Docker daemon  30.44MB
Step 1/9 : FROM duckietown/challenge-aido1_lf1-template-ros:v3
 ---> e739aec5cb73
Step 2/9 : RUN ["cross-build-start"]
 ---> Using cache
 ---> 271738377b7f
Step 3/9 : COPY solution.py ./
 ---> Using cache
 ---> a5e60ecd1d74
Step 4/9 : COPY rosagent.py ./
 ---> Using cache
 ---> df3510db62f0
Step 5/9 : COPY lf_slim.launch ./
 ---> Using cache
 ---> 2e8f16bbb4fb
Step 6/9 : ENV DUCKIETOWN_SERVER=evaluator
 ---> Using cache
 ---> 8914e0ef09ae
Step 7/9 : RUN ["cross-build-end"]
 ---> Using cache
 ---> 35e737f9c0e0
Step 8/9 : ENTRYPOINT ["qemu3-arm-static"]
 ---> Using cache
 ---> 11feebfc2b5b
Step 9/9 : CMD ["/bin/bash", "-ci", "./solution.py"]
 ---> Using cache
 ---> dd17eaaa9e73
Successfully built dd17eaaa9e73
Successfully tagged myimage:latest
INFO:runner-local:steps: [u'step1-simulation', u'step2-scoring', u'step3-videos', u'step4-viz']
INFO:runner-local:Now considering step "step1-simulation"
DEBUG:evaluator:Running: docker-compose -p project14 config
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 160, in runner_local_main_
    do_pull=do_pull)
  File "/project/src/duckietown_challenges_runner/runner.py", line 452, in run_single
    config_validated = run_docker(wd, project, ['config'], get_output=True)
  File "/project/src/duckietown_challenges_runner/runner.py", line 863, in run_docker
    tee_stdout = Tee('docker-stdout.txt', sys.stdout)
  File "/project/src/duckietown_challenges_runner/runner.py", line 829, in __init__
    self.file = open(name, 'wb')
IOError: [Errno 30] Read-only file system: 'docker-stdout.txt'



dts :  message from server: Last blog post:
    :                     :
    :                     :   Update to challenge LF, LFV evaluation code
    :                     : https://www.duckietown.org/archives/29549
DEBUG:dts:monitoring graceful exit
```

**Comment by placaille** [comment]
@AndreaCensi it works! Thanks 😄
