### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED eror

### ISSUE THREAD

**Issue by lapandic** [duckietown/duckietown-shell-commands#77]
I see the following error while trying to make a submission to LFV challenge.

```dts :  Traceback (most recent call last):
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/dt_command_abs.py", line 53, in do_command
    :      cls.command(shell, args)
    :    File "/home/dzenan/.dt-shell/commands/challenges/submit/command.py", line 166, in command
    :      submission_id = dtserver_submit(token, sub_info.challenge_name, data)
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/remote.py", line 145, in dtserver_submit
    :      return make_server_request(token, endpoint, data=data, method=method)
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/remote.py", line 88, in make_server_request
    :      raise_wrapped(ConnectionError, e, msg)
    :    File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/utils.py", line 43, in raise_wrapped
    :      raise e
    :  ConnectionError: Cannot connect to server https://challenges.duckietown.org/v3/submissions
    :  | Traceback (most recent call last):
    :  |   File "/home/dzenan/dt/challenge-aido1_LF1-baseline-duckietown/src/duckietown-shell/lib/dt_shell/remote.py", line 80, in make_server_request
    :  |     res = urllib.request.urlopen(req, timeout=timeout)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    :  |     return opener.open(url, data, timeout)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 429, in open
    :  |     response = self._open(req, data)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    :  |     '_open', req)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    :  |     result = func(*args)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    :  |     context=self._context)
    :  |   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    :  |     raise URLError(err)
    :  | URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"
```

Also the access at challenges.duckietown.org is not via https anymore. I guess this is related.

**Comment by AndreaCensi** [comment]
ssl should be fixed
